// Shared state type for the vendor-neutral SDR SDRAM controller.
package sdram_defs;

    typedef enum logic [5:0] {
        SDRAM_POWERUP, SDRAM_INIT_PRE, SDRAM_INIT_PRE_WAIT, SDRAM_INIT_REF1, SDRAM_INIT_REF1_WAIT,
        SDRAM_INIT_REF2, SDRAM_INIT_REF2_WAIT, SDRAM_INIT_MODE, SDRAM_INIT_MODE_WAIT,
        SDRAM_CLEAR_CHECK, SDRAM_CLEAR_PRE, SDRAM_CLEAR_PRE_WAIT, SDRAM_CLEAR_ACT, SDRAM_CLEAR_ACT_WAIT,
        SDRAM_CLEAR_WRITE, SDRAM_CLEAR_TERM,
        SDRAM_IDLE, SDRAM_ACT, SDRAM_ACT_WAIT, SDRAM_READ_CMD, SDRAM_READ_WAIT,
        SDRAM_READ_DATA, SDRAM_READ_SERVE, SDRAM_WRITE_COLLECT, SDRAM_WRITE_CMD, SDRAM_WRITE_DATA,
        SDRAM_BURST_TERM, SDRAM_COMPLETE,
        SDRAM_REFRESH_PRE, SDRAM_REFRESH_PRE_WAIT, SDRAM_REFRESH, SDRAM_REFRESH_WAIT,
        SDRAM_CLOSE, SDRAM_CLOSE_WAIT
    } SDRAMState;

endpackage : sdram_defs
