# By Emet Behrendt

"""Generate the PST readmemh file used by RTL and test benches."""

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
PST_WORD_BITS = 10
PST_JSON_PATH = ROOT / "hardware" / "data" / "pst_values" / "pst_values.json"
PST_HEX_PATH = ROOT / "hardware" / "data" / "pst_values" / "pst_values.hex"
PST_SV_PATH = ROOT / "hardware" / "rtl" / "generated" / "pst_values_pkg.sv"
MATERIAL_SV_PATH = ROOT / "hardware" / "rtl" / "generated" / "evaluation_parameters.svh"
PIECE_ORDER = ["pawn", "knight", "bishop", "rook", "queen", "king"]


def load_pst_words(json_path):
    with json_path.open() as f:
        data = json.load(f)

    pst = data["pst"]
    mem = [0] * (len(PIECE_ORDER) * 64)

    for piece_idx, piece in enumerate(PIECE_ORDER):
        table = pst[piece]
        if len(table) != 64:
            raise ValueError(f"PST for {piece} has {len(table)} entries, expected 64")

        for square, value in enumerate(table):
            if not isinstance(value, int) or not -(1 << (PST_WORD_BITS - 1)) <= value < (1 << (PST_WORD_BITS - 1)):
                raise ValueError(f"PST value for {piece} square {square} does not fit signed {PST_WORD_BITS} bits: {value}")
            mem[(piece_idx << 6) | square] = value

    return mem


def load_material_values(json_path):
    """Load the canonical material values in PieceType order."""
    with json_path.open() as f:
        material = json.load(f)["material"]
    if set(material) != set(PIECE_ORDER):
        raise ValueError("material must define exactly the six chess piece types")
    values = [material[piece] for piece in PIECE_ORDER]
    if any(not isinstance(value, int) or not -32768 <= value <= 32767 for value in values):
        raise ValueError("material values must be signed 16-bit integers")
    return values


def write_readmemh(words, out_path, word_bits=PST_WORD_BITS):
    hex_digits = (word_bits + 3) // 4
    mask = (1 << word_bits) - 1

    with out_path.open("w") as f:
        for word in words:
            f.write(f"{word & mask:0{hex_digits}X}\n")


def write_sv_package(words, out_path, word_bits=PST_WORD_BITS):
    hex_digits = (word_bits + 3) // 4
    mask = (1 << word_bits) - 1
    out_path.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "// Generated by hardware/scripts/generate_pst_values.py; do not edit by hand.",
        "",
        "package pst_values_pkg;",
        "",
        "    import general_chess_defs::*;",
        "",
        "    function automatic PstScore pst_value(input logic [8:0] addr);",
        "        case (addr)",
    ]
    for idx, word in enumerate(words):
        lines.append(f"            9'd{idx}: return PstScore'({word_bits}'sh{word & mask:0{hex_digits}X});")
    lines.extend(
        [
            "            default: return PstScore'(0);",
            "        endcase",
            "    endfunction : pst_value",
            "",
            "endpackage : pst_values_pkg",
            "",
        ]
    )
    out_path.write_text("\n".join(lines), encoding="ascii")


def write_material_include(values, out_path):
    """Generate the RTL material table from the same JSON as the PST."""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    literals = ["'d0", *(f"-'d{-value}" if value < 0 else f"'d{value}" for value in values), "'dx"]
    lines = [
        "// Generated by hardware/scripts/generate_pst_values.py; do not edit by hand.",
        "// Material values are in units of 1/128 pawn and indexed by PieceType.",
        "localparam EvalScore PIECE_VALS_128[8] = '{",
        "\t" + ", ".join(literals),
        "};",
        "",
    ]
    out_path.write_text("\n".join(lines), encoding="ascii")


def main():
    words = load_pst_words(PST_JSON_PATH)
    material = load_material_values(PST_JSON_PATH)
    write_readmemh(words, PST_HEX_PATH)
    write_sv_package(words, PST_SV_PATH)
    write_material_include(material, MATERIAL_SV_PATH)
    print(f"Wrote PST HEX to {PST_HEX_PATH}")
    print(f"Wrote PST SV package to {PST_SV_PATH}")
    print(f"Wrote material SV include to {MATERIAL_SV_PATH}")


if __name__ == "__main__":
    main()
