// megafunction wizard: %RAM: 1-PORT%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: altsyncram 

// ============================================================
// File Name: ram_1_port.v
// Megafunction Name(s):
// 			altsyncram
//
// Simulation Library Files(s):
// 			altera_mf
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
// ^^ Disregarded ^^
//
// 23.1std.1 Build 993 05/14/2024 SC Lite Edition
// ************************************************************

// A basic 1 port RAM with parameter sizes

// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on
module ram_1_port 
	#(
		parameter NUM_WORDS,
		parameter WORD_SIZE
	) (
		address,
		clock,
		data,
		wren,
		q
	);

	input	[$clog2(NUM_WORDS)-1:0]  address;
	input	  clock;
	input	[WORD_SIZE-1:0]  data;
	input	  wren;
	output	[WORD_SIZE-1:0]  q;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri1	  clock;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire [WORD_SIZE-1:0] sub_wire0;
	wire [WORD_SIZE-1:0] q = sub_wire0[WORD_SIZE-1:0];

	altsyncram #(
		.clock_enable_input_a("BYPASS"),
		.clock_enable_output_a("BYPASS"),
		.intended_device_family("Cyclone V"),
		.lpm_hint("ENABLE_RUNTIME_MOD=NO"),
		.lpm_type("altsyncram"),
		.numwords_a(NUM_WORDS),
		.operation_mode("SINGLE_PORT"),
		.outdata_aclr_a("NONE"),
		.outdata_reg_a("UNREGISTERED"),
		.power_up_uninitialized("TRUE"),
		.read_during_write_mode_port_a("NEW_DATA_NO_NBE_READ"),
		.widthad_a($clog2(NUM_WORDS)),
		.width_a(WORD_SIZE),
		.width_byteena_a(1)
	) altsyncram_component (
		.address_a (address),
		.clock0 (clock),
		.data_a (data),
		.wren_a (wren),
		.q_a (sub_wire0),
		.aclr0 (1'b0),
		.aclr1 (1'b0),
		.address_b (1'b1),
		.addressstall_a (1'b0),
		.addressstall_b (1'b0),
		.byteena_a (1'b1),
		.byteena_b (1'b1),
		.clock1 (1'b1),
		.clocken0 (1'b1),
		.clocken1 (1'b1),
		.clocken2 (1'b1),
		.clocken3 (1'b1),
		.data_b (1'b1),
		.eccstatus (),
		.q_b (),
		.rden_a (1'b1),
		.rden_b (1'b1),
		.wren_b (1'b0)
	);

endmodule
